apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urlshort
resources: [namespace.yaml, config.yaml, postgres.yaml, redis.yaml, app.yaml]
images:
  - name: urlshort
    newName: ghcr.io/YOUR_GITHUB_USERNAME/urlshort-platform
    newTag: latest
